# Generated by Django 5.2.3 on 2026-09-26 19:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0018_gascylinderconfig'),
        ('mobile_push', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceAlertSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField(default=0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceAlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=40)),
                ('comparison', models.CharField(max_length=3)),
                ('threshold', models.FloatField()),
                ('triggered', models.BooleanField(default=False)),
                ('last_reading_at', models.DateTimeField(null=True)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='mobile_push.devicealertsettings')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceThresholdEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('reading_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_push.devicealertrule')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceThresholdDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(null=True)),
                ('last_error', models.CharField(blank=True, max_length=100)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_push.pushinstallation')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_push.devicethresholdevent')),
            ],
        ),
        migrations.AddConstraint(
            model_name='devicealertsettings',
            constraint=models.UniqueConstraint(fields=('user', 'device'), name='personal_device_alert_settings'),
        ),
        migrations.AddConstraint(
            model_name='devicealertrule',
            constraint=models.UniqueConstraint(fields=('settings', 'metric', 'comparison', 'threshold'), name='personal_device_alert_rule'),
        ),
        migrations.AddConstraint(
            model_name='devicethresholdevent',
            constraint=models.UniqueConstraint(fields=('rule', 'reading_at'), name='unique_device_threshold_event'),
        ),
        migrations.AddConstraint(
            model_name='devicethresholddelivery',
            constraint=models.UniqueConstraint(fields=('event', 'installation'), name='unique_device_threshold_delivery'),
        ),
    ]
